apiVersion: v1
kind: Service
metadata:
  name: ms-service
spec:
  type: NodePort
  selector:
    app: metrics-server
  ports:
  - name: rest
    port: 80
    targetPort: 80
    nodePort: 30001
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-server
  labels:
    app: metrics-server
spec:
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
    spec:
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: procfs
        hostPath:
          path: /proc
          type: Directory
      containers:
        - image: vpemfh7/metrics-server
          imagePullPolicy: IfNotPresent
          name: metrics
          volumeMounts:
          - name: procfs
            mountPath: /procfs
            readOnly: true
          - name: sys
            mountPath: /sys
            readOnly: true
          ports:
            - name: http
              containerPort: 80
          env:
          - name: IFACE
            value: "ens33"
          ports:
            - name: rest
              containerPort: 80
