apiVersion: v1
kind: Service
metadata:
  name: ms-service
spec:
  clusterIP: None
  selector:
    app: metrics-server
  ports:
  - name: rest
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-server
  labels:
    app: metrics-server
spec:
  selector:
    matchLabels:
      app: metrics-server
  template:
    metadata:
      labels:
        app: metrics-server
    spec:
      containers:
        - image: vpemfh7/metrics-server
          name: metrics
          args: ["0.0.0.0", "80"]
          env:
          - name: HOSTNAME
            value: "teste"
          ports:
            - name: rest
              containerPort: 80
