apiVersion: v1
kind: Service
metadata:
  name: web-deploy
spec:
  type: NodePort
  selector:
    app: web-deploy
  ports:
  - name: rest
    port: 80
    targetPort: 80
    nodePort: 30002
---    
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: web-deploy
#   labels:
#     app: web-deploy
# spec:
#   replicas: 4
#   selector:
#     matchLabels:
#       app: web-deploy
#   template:
#     metadata:
#       labels:
#         app: web-deploy
#     spec:
#       schedulerName: teste
#       containers:
#         - image: nginx
#           imagePullPolicy: IfNotPresent
#           name: web
---
apiVersion: v1
kind: Pod
metadata:
  name: web-deploy
  labels:
    app: web-deploy
spec:
  schedulerName: teste
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: web
