apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-deploy
  template:
    metadata:
      labels:
        app: web-deploy
      annotations:
        schedulePolicy: bestfit
    spec:
      containers:
        - image: nginx
          name: web
      schedulerName: horchulhack