apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: web-deploy
  labels:
    app: web-deploy
spec:
  selector:
    matchLabels:
      app: web-deploy
  template:
    metadata:
      labels:
        app: web-deploy
    spec:
      schedulerName: teste
      containers:
        - image: nginx
          name: web
