apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: web-deploy
  labels:
    app: web-deploy
spec:
  selector:
    matchLabels:
      app: web-deploy
  template:
    metadata:
      labels:
        app: web-deploy
      annotations:
        schedulePolicy: bestfit
        ph.cpu: 8
        ph.memory: 0.75
        ph.network: 0.75
        ph.disk: 0.75
    spec:
      schedulerName: horchulhack
      containers:
        - image: nginx
          name: web
