apiVersion: v1
kind: Service
metadata:
  name: web-deploy
spec:
  type: NodePort
  selector:
    app: web-deploy
  ports:
  - name: rest
    port: 80
    targetPort: 80
    nodePort: 30002
---
apiVersion: v1
kind: Pod
metadata:
  name: web-deploy
  labels:
    app: web-deploy
spec:
  schedulerName: tcc
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: web
